version: 2
jobs:
  build:
    branches:
      only:
        - master
      ignore:
        - gh-pages
    docker:
      - image: circleci/node:10
    steps:
      - add_ssh_keys:
          fingerprints:
            - "cf:91:42:55:b6:c8:70:f7:c3:18:ad:c1:30:e5:2c:73"
      - checkout
      - run:
          name: git config
          command: |
            git config user.email "ci-build@lemoncode.net"
            git config user.name "ci-build"
      - run:
          name: Install and deploy
          command: |
            cd ./website
            npm install
            npm run deploy
